db:
  image: postgres:9.4.1
  ports: 
    - "5432:5432"
redis:
  image: redis:3.0.3
  ports:
    - "6379:6379"
web:
  build: .
  command: bin/rails server -p 4567 -b '0.0.0.0'
  volumes:
    - .:/app/ecommerce
  ports:
    - 4567:4567
  links:
    - db
    - redis